### PR TITLE
fix: Nerdgraph errors deprecation

### PR DESCRIPTION
**Pull request by rudouglas**
This replaces `errors` with `error?.graphQLErrors` were applicable, as part of this deprecation ticket:

fixes https://github.com/newrelic/nr1-catalog/issues/305

### CODE REVIEW

**Comment by zstix** [comment]
@jospdeleon does this look good to you?

**Comment by jpvajda** [comment]
I've reached out @jospdeleon via our 3rd party app help channel to confirm the review of this change.

**Review by jpvajda — APPROVED** [review]

**Comment by jpvajda** [comment]
I confirmed with @jospdeleon and she said by 3/18 she'd be able to review this PR to approve the merge.

**Review by jpvajda — CHANGES_REQUESTED** [review]
waiting on review from @jospdeleon before merging.

**Comment by jospdeleon** [comment]
@jpvajda I made a slight change and merged the rest.

**Pull request merged**
